language: node_js
node_js:
  - "6.6"
cache:
  npm: false
  directories:
    - .lib/node_modules
install:
  - make install
script:
  - make test
notifications:
  email:
    recipients:
      - ezpaarse-team@googlegroups.com
      - dominique.lechaudel@gmail.com
    on_success: change
    on_failure: always
  slack: 'inist-dpi:53Jp5iUZeRidSGZn0TukMSKo#activity'
